name: vital_devices_ios
description: The ios implementation of Vital Devices.
version: 1.1.10
homepage: https://tryvital.io/
repository: https://github.com/tryVital/vital-flutter

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    implements: vital_devices
    platforms:
      ios:
        pluginClass: VitalDevicesPlugin

dependencies:
  flutter:
    sdk: flutter
  vital_core: ^1.5.4
  vital_devices_platform_interface: ^1.1.11
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  fimber: ^0.6.6
