name: vital_flutter
repository: https://github.com/tryVital/vital-flutter

command:
  bootstrap:
    usePubspecOverrides: true

packages:
  - packages/**
  - example

scripts:
  analyze: melos exec -- flutter analyze
  format: melos exec -- flutter format .
  postclean: >
    melos exec --flutter --concurrency=3 -- "flutter clean"
