name: Publish

jobs:
  pub_dev_publish_check:
    name: "Publish to pub.dev"
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: |
          ./.github/workflows/scripts/install-tools.sh
      - name: "Bootstrap Workspace"
        run: melos bootstrap
      - name: "Pub Check"
        run: |
          melos exec -c 1 --no-private --ignore="*example*" -- \
            flutter pub publish --dry-run
